services:
  backend:
    develop:
      watch:
        - action: sync+restart
          path: ./backend
          target: /app
          ignore:
            - node_modules/
    ports: 
    - 4000:4000

  frontend:
    build:
      context: frontend
      target: development
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules/
    ports:
    - 3000:3000
    environment:
      - VITE_BACKEND_URL=http://localhost:4000