services:
  backend:
    ports: 
    - 4000:4000

  frontend:
    build:
      context: frontend
      target: development
    ports:
    - 3000:3000
    environment:
      - VITE_BACKEND_URL=http://localhost:4000